#' Import a file created by a WALZ GFS3000 gas exchange system
#'
#' Imports gas exchange or chart-trace files generated by a WALZ GFS3000 gas exchange system. 
#'
#' @param file a csv file generated by the Walz GFS3000 gas exchange system
#' @param load Indicates which element of the GFS output to import. Either "all", for everything, or "MP", for measurement points only. "Trace" is used to specify the file is a chart trace, not a measurement file. "Default is "all".
#' @return Depends on the parameter for \code{load}. Either a list containing three data frames: "ZP" for Zeropoints, i.e. the calibration data, "MP" for the measurement points, i.e. the hopefully meaningful data, and "Units" with a vector of the units to accompany the data. Or, if the "import" argument is set to "MP" or "trace", just a dataframe with the measurement points.
#' @export

ImportGFS <- function(file, load = "all") {

# file structure: 
# 1 row header
# 1 row units
# many rows data 
# delimiter is ";"

  stopifnot(load %in% c("all", "MP", "trace"))
  data <- utils::read.csv(file = file,
              header = FALSE,
              sep = ";",
              skip = 2)

  header <- readLines(con = file)
  header <- as.character(header[1])
  header <- enc2utf8(header)
  header <- unlist(strsplit(header, ";"))
  names(data) <- header
  
  if (load == "trace") {
    names(data) <- gsub('"', '', names(data))
  }

  units <- readLines(con = file)
  units <- as.character(units[2])
  units <- enc2utf8(units)
  units <- unlist(strsplit(units, ";"))

# add filename to the data
  data$filename <- basename(file)

# convert and format datetime
  if(load != "trace") {
  data$DateTime <- paste(data$Date, data$Time, sep = " ")
  data$DateTime <- as.POSIXct(data$DateTime)
} else {
  data$Time <- as.POSIXct(data$Time, format = "%H:%M:%S")
}

# separate Zeropoints and measurement points
  if (load != "trace") {
  isZP <- grep("^ZP", data$Code)
  isMP <- grep("^MP", data$Code)
  ZP   <- data[isZP, ]
  data <- data[isMP, ]
  }
  
# assemble output
  if (load == "all") {
     out <- list(ZP = ZP,
                 MP = data,
                 Units = units) 
  } 
  if (load == "MP") {
        out <- data
  }
  if (load == "trace") {
        out <- data
  }
  return(out)
}

